### ISSUE TITLE
CORS not work on laravelfly, but works on php-fpm

### ISSUE THREAD

**Issue by chenzeshu** [scil/LaravelFly#11]
1. `laravelFly`在9501端口正常启动，
2. 设置`nginx`反向代理到9501, 本地请求成功，
3. 已经有`CORS.php`中间件并在`kernel`注册,  `PHP-FPM`模式下可以跨域. 但使用`laraveFly`后不能跨域。

请问有跨域方面的尝试吗, 或者提示也行...
PS：`laravoole`也不能跨域

**Comment by scil** [comment]
maybe laravelfly server only listen localhost  by default.
could you show some code?

**Comment by chenzeshu** [comment]
thx for your reply!   here is my environment:

- laravel v5.5;
 - homestead v4.0.1;
 - laravelfly server running at 0.0.0.0:9501;
 - my vue2-client with axios running at localhost:8080
 and then everything else are setted as you told in `readme.md`

- my CORS.php
```
<?php
namespace App\Http\Middleware;
use Closure;
class Cors
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        $domains = ['http://localhost:8080'];
        if(isset($request->server()['HTTP_ORIGIN'])){
            $origin = $request->server()['HTTP_ORIGIN'];
            if (in_array($origin, $domains)) {
                header('Access-Control-Allow-Origin: '.$origin);
                header('Access-Control-Allow-Headers: Origin, Content-Type, Authorization, X-Hub-Signature');
                header('Access-Control-Allow-Methods: GET, POST, OPTIONS, PUT, PATCH, DELETE');
                header('Access-Control-Expose-Headers: Authorization, username, jwtToken');
            }
        }
        return $next($request);
    }
}
```
## good msg
laravelfly-server works well when not cross domain(using laravel's MVC blade itself) ;

## Question
 - my front and back communicates well when using PHP-FPM but as soon as I switch to laravelfly-server the browser throws out a CORS exception which tells  `localhost:8080 is therefore not allowed access`.
- and I try `dd()` in my `CORS.php` but get no result;

so I guess when in the situation of CORS  there were some problem with `$request`?

thx for notice and wating for new reply!

**Comment by scil** [comment]
please try laravel api like
```
    public function handle($request, Closure $next)
    {
        $response = $next($request);

        return response($content)
            ->header('Content-Type', $type)
            ->header('X-Header-One', 'Header Value')
            ->header('X-Header-Two', 'Header Value');
    }

```
