### ISSUE TITLE
does LaravelFly support lumen

### ISSUE THREAD

**Issue by sayid** [scil/LaravelFly#12]
我们公司的项目是基于lumen框架的，直接使用swoole会造成数据污染，连接之间的数据会相互干扰。看了您的帖子谈到了这个问题。这个项目能直接移植到lumen下吗

**Comment by scil** [comment]
You can test Mode Simple.
I'm working on Mode Coroutine which is still under development.

**Comment by sayid** [comment]
how do i config app.php to support lumen?

**Comment by hhxsv5** [comment]
[LaravelS](https://github.com/hhxsv5/laravel-s) supports both Laravel & Lumen.
