### ISSUE TITLE
preload error: the name is already in use

### ISSUE THREAD

**Issue by stevenyangecho** [scil/LaravelFly#14]
`[INFO] include: /project/bootstrap/cache/laravelfly_preload.php

Fatal error: Cannot declare class Monolog\Handler\AbstractHandler, because the name is already in use in /project/bootstrap/\cache/laravelfly_preload.php on line 16140`

**Comment by scil** [comment]
It's fixed, update and then delete bootstrap/cache/laravelfly_preload.php

**Comment by stevenyangecho** [comment]
updated,and run composer update. composer dumpautoload and deleted bootstrap/cache/laravelfly_preload.php.
and...still wrong..
`Fatal error: Cannot declare class Monolog\Handler\AbstractHandler, because the name is already in use in /project/bootstrap/cache/laravelfly_preload.php on line 18869`

**Comment by scil** [comment]
which mode do you use, Simple or Map?
You can try to set 'compile' => false in  fly.conf.php

**Comment by stevenyangecho** [comment]
I use the simple mode.
and yes. set compile=>false,then its ok.
i'm use laravel  5.5.40
