### ISSUE TITLE
laravel 5.6,  [ERROR] bootstrap: Error:  服务器无法启动

### ISSUE THREAD

**Issue by blakelu** [scil/LaravelFly#15]
[ERROR] bootstrap: Error: Call to undefined method Illuminate\Log\LogServiceProvider::coroutineFriendlyServices() in /Users/liupeng/Site/quding/vendor/scil/laravel-fly/src/LaravelFly/Map/Bootstrap/LoadConfiguration.php:56
Stack trace:
#0 /Users/liupeng/Site/quding/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(206): LaravelFly\Map\Bootstrap\LoadConfiguration->bootstrap(Object(LaravelFly\Simple\Application))
#1 /Users/liupeng/Site/quding/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(162): Illuminate\Foundation\Application->bootstrapWith(Array)
#2 /Users/liupeng/Site/quding/vendor/scil/laravel-fly/src/LaravelFly/Server/HttpServer.php(59): Illuminate\Foundation\Http\Kernel->bootstrap()
#3 {main}

**Comment by scil** [comment]
Did you use Mode Simple? It's fixed.  Try the lastest agagin.

And LaravelFly is now supporting laravel 5.5.
