### ISSUE TITLE
Can't find fly executable

### ISSUE THREAD

**Issue by aftabnaveed** [scil/LaravelFly#18]
I successfully installed the LaravelFly via
`composer require "scil/laravel-fly":"dev-master"`

But when when I goto vendor/bin/ folder I don't see 

the `fly` executable there What could I be doing wrong here?

**Comment by aftabnaveed** [comment]
I am able to find it here, but the documentation here seems to be very confusing and does not tell you anything about it.

`vendor/scil/laravel-fly/bin/fly`

**Comment by scil** [comment]
It's a php script. 

see: https://github.com/scil/LaravelFly/blob/master/doc/server.md

**Comment by aftabnaveed** [comment]
I think it makes sense to organize the documentation a little bit and categorize it. I would suggest this convention if you approve I can then organize it once I am able to use the Package in my website :)

1. Installation
2. Configuration
3. Commands

**Comment by aftabnaveed** [comment]
As for as the executable is concerned I think automated symlink should be created inside the vendor/bin folder or wherever the composer specifies the bin.

**Comment by scil** [comment]
Thank you very much. Yes, the doc should be improved.

Monthes ago, there was a script file inside vendor/bin. But I thought it's not clear that the LaravelFly server is a php script which can be debugged, so I dropped it.
