### ISSUE TITLE
XDebug

### ISSUE THREAD

**Issue by aftabnaveed** [scil/LaravelFly#19]
According to the documentation of Swoole version greater than 2.0 will not work with xdebug but I see you mentioned the xdebug config here https://github.com/scil/LaravelFly/blob/master/doc/server.md are you able to find a work around for it?

**Comment by scil** [comment]
yes, you can try xdebug sometimes, except swoole coroutine.

I'm waiting for swoole 4.0 which maybe support xdebug.
