### ISSUE TITLE
The second question: cpu

### ISSUE THREAD

**Issue by jonny77** [scil/LaravelFly#2]
My mac probook 
ram:8G ram
cpu: i5 
when i use your default config in laravelfly.server.php , cpu   goes up  to  nearly 100%  , when i change to config below , about 30% down ,is there anything wrong in your script ? 
<?php

const LARAVELFLY_KERNEL= '\App\Http\Kernel';

// Normal Mode or Greedy Mode
const LARAVELFLY_GREEDY = true;

/**
- When to load 'compiled.php'
- If true, compiled.php is loaded before any swoole worker. No matter how many workers, there's only one copy in memory. The merit is saving some memory . The demerit is , memory does not update when you restart all workers.
- If false, compiled.php is loaed on each worker start.Each worker has compiled codes in memory. The merit is , if compiled.php changes, you can restart all workers to use new codes.
  */
  const LOAD_COMPILED_BEFORE_WORKER = false;

// when true, Application::runningInConsole() return false.
const FAKE_NOT_IN_CONSOLE = false;

// this array is used for swoole server, see more option list at swoole doc.
return [
    // 'listen_ip' => '0.0.0.0',// listen to any address
    'listen_ip' => '127.0.0.1',// listen only to localhost

```
'listen_port' => 9501,

// like pm.max_children in php-fpm, but there's no option like pm.start_servers
//'worker_num' => 4,
'worker_num' => 2,
// set it to false when debug, otherwise true
'daemonize' => true,

// like pm.max_requests in php-fpm
// 'max_request' =>1000,
'max_request' =>100,

//'log_file' => '/data/log/swoole.log',
```

];

**Comment by scil** [comment]
config depend on env.

I use corei5 , run laravelfly in virtualbox host  , and everything works fine.

And 'max_request' / 'worker_num'  are from [swoole](https://github.com/swoole/swoole-src)  , not related to laravelfly script.

Thank for your reply.

**Comment by monkeycraps** [comment]
my cpu go to 100% too 
it cost the user cpu
i use swoole 1.7.8, mac os, laravel 5.2, php5.5.6 
laravefly latest, and default setting 
it change when i change the worker_num, it seems 1 worker take 15% cpu usage from my sys 

![image](https://cloud.githubusercontent.com/assets/2322555/18643303/175c6dea-7ed7-11e6-8607-11729ce07e6a.png)
![image](https://cloud.githubusercontent.com/assets/2322555/18643309/1c57f53a-7ed7-11e6-9924-1dbea08b190c.png)

**Comment by monkeycraps** [comment]
if i use LARAVELFLY_GREEDY = false 
it will be ok
