### ISSUE TITLE
LaravelFly containes blocking code?

### ISSUE THREAD

**Issue by gouchaoer** [scil/LaravelFly#22]
能兼容laravel很好，问题是协程中不能使用任何阻塞的代码，数据库、redis以及rpc等都不能是阻塞的，但是我并没有看到有协程客户端封装，如果用的laravel原生的就会有问题吧

**Comment by gouchaoer** [comment]
阻塞在一个fpm worker处理一个http请求中没问题，但会导致同时处理很多http请求的swoole worker下别的http请求得不到调度

**Comment by scil** [comment]
swoole vs fpm?
The first advantage is preloading resources as much as possible.
LaravelFly has implemented mysql corotine client, but the pool is on the road.

And one of the LaravelFly design rules is that: same code can run on both fpm and swoole.
