### ISSUE TITLE
LaravelFly\Kernel path

### ISSUE THREAD

**Issue by tamer-hassan** [scil/LaravelFly#24]
https://github.com/scil/LaravelFly/blob/b19aa94240640d55d17efea81dee999d20d257be/src/LaravelFly/Server/Common.php#L74

'Http/Kernel.php' should now be just 'Kernel.php' ? since you moved the kernel a directory up before.

**Comment by scil** [comment]
I have moved it.

But 'Http/Kernel.php' should not be changed, as it's used for test https://github.com/scil/LaravelFly/blob/master/tests/Map/Feature/FlyFilesTest.php which is to trace differences in laravel official files.

'Http/Kernel.php' means there'is a file Kernel.php located dir Http  which is at https://github.com/scil/LaravelFly/tree/master/tests/offcial_files/5.5

**Comment by tamer-hassan** [comment]
what about the require here:
https://github.com/scil/LaravelFly/blob/b19aa94240640d55d17efea81dee999d20d257be/src/LaravelFly/Server/Common.php#L253

won't that fail to include `src/fly/Http/Kernel.php` because it is no longer there?

**Comment by scil** [comment]
```
            'Http/Kernel.php' =>
```
is in `$conditionFlyFiles` whoes items are included conditionally.

`src/fly/Kernel.php` is included when if (empty(LARAVELFLY_SERVICES['kernel']))
```
            if (empty(LARAVELFLY_SERVICES['kernel']))
                include_once $flyBaseDir . '../Kernel.php';
```

**Comment by tamer-hassan** [comment]
my mistake. I misread the code. Thanks for clarifying.
