### ISSUE TITLE
Database refactor & Postgresql support

### ISSUE THREAD

**Issue by tamer-hassan** [scil/LaravelFly#25]
Is there any plans to add support for Postgresql?

Currently I see for mysql using `SwooleMySQLConnection` & `CoroutineMySQLConnector` from `Hhxsv5\LaravelS\Illuminate\Database`

Coroutine Postgresql also supported in Swoole since > 6 months ago:
https://github.com/swoole/swoole-src/blob/master/examples/postgresql/postgresql_coro.php

I can make a PR to add it, if you like?

**Comment by scil** [comment]
Good idea! Very welcome.

By the way, coroutine db is not yet ready for production.  connection pool is expected. I'm still waiting for 
 [laravel-s](https://github.com/hhxsv5/laravel-s/tree/d5f035c598c0a605a59c1f68c50068b21523d610) who plans to make connection pool.

**Comment by tamer-hassan** [comment]
Looks like the feature/connection_pool branch in LaravelS hasn't been updated since 2 weeks, and only 1 commit.
https://github.com/hhxsv5/laravel-s/compare/feature/connection_pool
😞

**Comment by scil** [comment]
Some frameworks , such as [swoft](https://github.com/swoft-cloud/swoft), have got connection pool alreay.

so I think it maybe not too hard.

but I still focus on safety. Hope this [safety checklist](https://github.com/scil/LaravelFly/wiki/Checklist-For-Safety) have some values.

**Comment by scil** [comment]
connection pool is ready.

 I use mysql.  you can test Postgresql.

**Comment by tamer-hassan** [comment]
thank you @scil
