### ISSUE TITLE
support laravel5.6 5.7

### ISSUE THREAD

**Issue by zhenyangze** [scil/LaravelFly#26]
## composer require scil/laravel-fly
Using version ^0.9.2 for scil/laravel-fly
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

## Problem 1
    - scil/laravel-fly-files v5.5.4302 requires laravel/framework 5.5.43 -> satisfiable by laravel/framework[v5.5.43] but these conflict with your requirements or minimum-stability.
    - scil/laravel-fly-files v5.5.4301 requires laravel/framework 5.5.43 -> satisfiable by laravel/framework[v5.5.43] but these conflict with your requirements or minimum-stability.
    - scil/laravel-fly-files v5.5.43 requires laravel/framework 5.5.43 -> satisfiable by laravel/framework[v5.5.43] but these conflict with your requirements or minimum-stability.
    - scil/laravel-fly-files v5.5.4001 requires laravel/framework 5.5.40 -> satisfiable by laravel/framework[v5.5.40] but these conflict with your requirements or minimum-stability.
    - scil/laravel-fly-files 5.5.x-dev requires laravel/framework 5.5.43 -> satisfiable by laravel/framework[v5.5.43] but these conflict with your requirements or minimum-stability.
    - Installation request for scil/laravel-fly ^0.9.2 -> satisfiable by scil/laravel-fly[v0.9.2].
    - Can only install one of: laravel/framework[v5.6.35, v5.6.28].
    - Can only install one of: laravel/framework[v5.6.28, v5.6.35].
    - Can only install one of: laravel/framework[v5.6.28, v5.6.35].
    - scil/laravel-fly-files 5.6.x-dev requires laravel/framework 5.6.28 -> satisfiable by laravel/framework[v5.6.28].
    - scil/laravel-fly v0.9.2 requires scil/laravel-fly-files 5.5.* || 5.6.* -> satisfiable by scil/laravel-fly-files[5.5.x-dev, 5.6.x-dev, v5.5.4001, v5.5.43, v5.5.4301, v5.5.4302, v5.6.38.1, v5.6.38.2].
    - scil/laravel-fly-files v5.6.38.1 requires laravel/framework 5.6.38 -> satisfiable by laravel/framework[v5.6.38].
    - scil/laravel-fly-files v5.6.38.2 requires laravel/framework 5.6.38 -> satisfiable by laravel/framework[v5.6.38].
    - Conclusion: don't install laravel/framework v5.6.38
    - Installation request for laravel/framework (locked at v5.6.35, required as 5.6.*) -> satisfiable by laravel/framework[v5.6.35].

Installation failed, reverting ./composer.json to its original content.

**Comment by scil** [comment]
try to require laravel 5.6.38,   not 5.6.35.

old versions not supported any more.

**Comment by ibrunotome** [comment]
Hi @scil, 5.7 still not supported.

**Comment by scil** [comment]
Laravel 5.7.25 will be supported.  now the newest is 5.7.19
