### ISSUE TITLE
Version compatibility issue with laravel 5.7.27

### ISSUE THREAD

**Issue by harishdurga** [scil/LaravelFly#30]
Laravel Version: 5.7.27
I ran the following command:
composer require "scil/laravel-fly":"dev-master"
I got the following error:
 Problem 1
    - scil/laravel-fly-files v5.6.39.4 requires laravel/framework 5.6.39 -> satisfiable by laravel/framework[v5.6.39] but these conflict with your requirements or minimum-stability.
    - scil/laravel-fly-files v5.6.39.3 requires laravel/framework 5.6.39 -> satisfiable by laravel/framework[v5.6.39] but these conflict with your requirements or minimum-stability.
    - scil/laravel-fly-files v5.6.39.2 requires laravel/framework 5.6.39 -> satisfiable by laravel/framework[v5.6.39] but these conflict with your requirements or minimum-stability.
    - scil/laravel-fly-files v5.6.39.1 requires laravel/framework 5.6.39 -> satisfiable by laravel/framework[v5.6.39] but these conflict with your requirements or minimum-stability.
    - scil/laravel-fly-files v5.6.38.7 requires laravel/framework 5.6.38 -> satisfiable by laravel/framework[v5.6.38] but these conflict with your requirements or minimum-stability.
    - scil/laravel-fly-files v5.6.38.6 requires laravel/framework 5.6.38 -> satisfiable by laravel/framework[v5.6.38] but these conflict with your requirements or minimum-stability.
    - scil/laravel-fly-files v5.6.38.5 requires laravel/framework 5.6.38 -> satisfiable by laravel/framework[v5.6.38] but these conflict with your requirements or minimum-stability.
    - scil/laravel-fly-files v5.6.38.4 requires laravel/framework 5.6.38 -> satisfiable by laravel/framework[v5.6.38] but these conflict with your requirements or minimum-stability.
    - scil/laravel-fly-files v5.6.38.3 requires laravel/framework 5.6.38 -> satisfiable by laravel/framework[v5.6.38] but these conflict with your requirements or minimum-stability.
    - scil/laravel-fly-files v5.6.38.2 requires laravel/framework 5.6.38 -> satisfiable by laravel/framework[v5.6.38] but these conflict with your requirements or minimum-stability.
    - scil/laravel-fly-files v5.6.38.1 requires laravel/framework 5.6.38 -> satisfiable by laravel/framework[v5.6.38] but these conflict with your requirements or minimum-stability.
    - scil/laravel-fly-files v5.5.4402 requires laravel/framework 5.5.44 -> satisfiable by laravel/framework[v5.5.44] but these conflict with your requirements or minimum-stability.
    - scil/laravel-fly-files v5.5.4401 requires laravel/framework 5.5.44 -> satisfiable by laravel/framework[v5.5.44] but these conflict with your requirements or minimum-stability.
    - scil/laravel-fly-files v5.5.4307 requires laravel/framework 5.5.43 -> satisfiable by laravel/framework[v5.5.43] but these conflict with your requirements or minimum-stability.
    - scil/laravel-fly-files v5.5.4306 requires laravel/framework 5.5.43 -> satisfiable by laravel/framework[v5.5.43] but these conflict with your requirements or minimum-stability.
    - scil/laravel-fly-files v5.5.4305 requires laravel/framework 5.5.43 -> satisfiable by laravel/framework[v5.5.43] but these conflict with your requirements or minimum-stability.
    - scil/laravel-fly-files v5.5.4304 requires laravel/framework 5.5.43 -> satisfiable by laravel/framework[v5.5.43] but these conflict with your requirements or minimum-stability.
    - scil/laravel-fly-files v5.5.4303 requires laravel/framework 5.5.43 -> satisfiable by laravel/framework[v5.5.43] but these conflict with your requirements or minimum-stability.
    - scil/laravel-fly-files v5.5.4302 requires laravel/framework 5.5.43 -> satisfiable by laravel/framework[v5.5.43] but these conflict with your requirements or minimum-stability.
    - scil/laravel-fly-files v5.5.4301 requires laravel/framework 5.5.43 -> satisfiable by laravel/framework[v5.5.43] but these conflict with your requirements or minimum-stability.
    - scil/laravel-fly-files v5.5.43 requires laravel/framework 5.5.43 -> satisfiable by laravel/framework[v5.5.43] but these conflict with your requirements or minimum-stability.
    - scil/laravel-fly-files v5.5.4001 requires laravel/framework 5.5.40 -> satisfiable by laravel/framework[v5.5.40] but these conflict with your requirements or minimum-stability.
    - scil/laravel-fly-files 5.6.x-dev requires laravel/framework 5.6.39 -> satisfiable by laravel/framework[v5.6.39] but these conflict with your requirements or minimum-stability.
    - scil/laravel-fly-files 5.5.x-dev requires laravel/framework 5.5.44 -> satisfiable by laravel/framework[v5.5.44] but these conflict with your requirements or minimum-stability.
    - scil/laravel-fly dev-master requires scil/laravel-fly-files 5.5.* || 5.6.* || 5.7.*  -> satisfiable by scil/laravel-fly-files[5.5.x-dev, 5.6.x-dev, v5.5.4001, v5.5.43, v5.5.4301, v5.5.4302, v5.5.4303, v5.5.4304, v5.5.4305, v5.5.4306, v5.5.4307, v5.5.4401, v5.5.4402, v5.6.38.1, v5.6.38.2, v5.6.38.3, v5.6.38.4, v5.6.38.5, v5.6.38.6, v5.6.38.7, v5.6.39.1, v5.6.39.2, v5.6.39.3, v5.6.39.4].
    - Installation request for scil/laravel-fly dev-master -> satisfiable by scil/laravel-fly[dev-master].

Installation failed, reverting ./composer.json to its original content.

**Comment by scil** [comment]
now it's supporting 5.7.25

**Comment by scil** [comment]
now it's supporting 5.7.28

**Comment by fannyfan414** [comment]
will you support laravel 5.8.*?

**Comment by fannyfan414** [comment]
> now it's supporting 5.7.28
will you support laravel 5.8.*?

**Comment by fannyfan414** [comment]
> now it's supporting 5.7.28

will you support laravel 5.8.*?

**Comment by scil** [comment]
Yes. Will.

**Comment by fannyfan414** [comment]
> Yes. Will.

wait for it :)
