### ISSUE TITLE
class Psy\Input\ShellInput not found

### ISSUE THREAD

**Issue by honglibin** [scil/LaravelFly#31]
When i execute `php vendor/scil/laravel-fly/bin/fly start`, the ternimal display error with
`Fatal error: Uncaught Error: Class 'Psy\Input\ShellInput' not found in /www/wwwroot/zdd/vendor/scil/laravel-fly/src/LaravelFly/Server/Traits/Console.php:38`

**Comment by scil** [comment]
This class is in package `psy/psysh` which is required by `laravel/tinker`

**Comment by honglibin** [comment]
thanks for you reply.
