### ISSUE TITLE
How do you solve the cached resolved instances for facade, it is supposed to be shared by multiple coroutines.

### ISSUE THREAD

**Issue by videni** [scil/LaravelFly#35]
The class ` \Illuminate\Support\Facades\Facade` will cache the resolved instances into $resolvedInstance variable , which might be available for another coroutine, I am wondering how this package resolve this issue, I checked all source codes, it seems there is no code for this logic, can anybody explain this please?

![image](https://github.com/scil/LaravelFly/assets/4058341/cc7fe06c-1b5d-4a13-9056-f5a9f6dbbdc5)

**Comment by scil** [comment]
rewrite all of the core files, like https://github.com/scil/LaravelFly-fly-files/blob/aa9e358a4679c14260414ce510ed296edc508236/src/Facade.php#L23

related doc:https://github.com/scil/LaravelFly/wiki/Data-Pollution

**Comment by videni** [comment]
@scil , thanks for reply,    I  read these doc, but still not understand.

 let's assume there are two coroutines:

Coroutine A sets its own application, when it calls  Log::info('bla....'), its own application instance will be used, but the log instance will be cached into the $resolveInstance variable,   then A slept somehow.  

Coroutine B also run the same code before coroutine A,   B recoverd,  it  calls  Log::info, since the $resolveInstance  is static, shared by two coroutines,   does the log instance that B uses created by coroutine A?

**Comment by scil** [comment]
`protected static $resolvedInstance = [];` is an nest array holding different arrays of instances for different coroutine

look at this
```
   static function initForRequestCorontine(int $cid)
    {
        static::$resolvedInstance[$cid] = static::$resolvedInstance[WORKER_COROUTINE_ID];
    }
```

`$cid` is the id for coroutine.

**Comment by videni** [comment]
@scil , I see, it is resonable,  I didn't find this code for Facade specifically, ` \Illuminate\Support\Facades\Facade`, can you show me the source code please?

**Comment by scil** [comment]
> @scil , I see, it is resonable, I didn't find this code for Facade specifically, ` \Illuminate\Support\Facades\Facade`, can you show me the source code please?

just in the link above

**Comment by videni** [comment]
@scil , I see,  thanks for your patience.
